../configure --prefix=/server/php/85/ \
--enable-fpm \
--with-fpm-user=php \
--with-fpm-group=php \
--with-fpm-systemd \
--with-openssl \
--with-openssl-legacy-provider \
--with-openssl-argon2 \
--with-zlib \
--with-curl \
--enable-exif \
--enable-gd \
--with-jpeg \
--with-freetype \
--enable-intl \
--enable-mbstring \
--with-mysqli=mysqlnd \
--with-pdo-mysql=mysqlnd \
--with-pdo-pgsql=/server/postgres \
--with-pgsql=/server/postgres \
--with-sodium \
--enable-sockets \
--with-password-argon2 \
--enable-mysqlnd > stdout.log
